### ISSUE TITLE
Current version in homebrew is not compatible with macOS Sierra

### ISSUE THREAD

**Issue by michaelstonis** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#55]
Currently, the homebrew package is built against version 2.0.0. Issue #46 prevents it from running properly. If you install 2.0.2 from source or manually, it works as expected.

**Comment by jeebseven** [comment]
I'm not quite sure if this is the same problem, but it is also incompatible as in Sierra git seems not to be able to locate / reach / interact with the OSX Keychain, due to the new OpenSSL stuff.

Therefore I thought this tool would be a nice "second" keystore, for storing my git credential crypted. As this tool also wants to store the credentials within the keychain this seems a bit outdated?

**Comment by darewreck54** [comment]
I tried 2.0.3 and it doesn't work?  Anyone have any luck?
